In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/DataPreprocessingGraded_dataset.csv')
df.head(10)

    V1    V2       V3    V4        V5 Target
0  2.0  50.0  12500.0  98.0  NEGATIVE    YES
1  0.0  13.0   3250.0  28.0  NEGATIVE    YES
2    ?     ?   4000.0  35.0  NEGATIVE    YES
3    ?  20.0   5000.0  45.0  NEGATIVE    YES
4  1.0  24.0   6000.0  77.0  NEGATIVE     NO
5  4.0     ?   1000.0   4.0  NEGATIVE     NO
6  2.0     ?   1750.0  14.0  NEGATIVE    YES
7    ?  12.0   3000.0  35.0  NEGATIVE     NO
8  2.0   9.0   2250.0  22.0  NEGATIVE    YES
9  5.0  46.0  11500.0  98.0  NEGATIVE    YES

In [3]:
df.isnull().sum().sum()
(df.values == '?').sum()

np.int64(0)

np.int64(10)

In [4]:
df.shape

(748, 6)

In [33]:
df = df.replace('?', np.nan)
df.isna().sum()

V1        5
V2        5
V3        0
V4        0
V5        0
Target    0
dtype: int64

In [6]:
df = df.astype({'V1': float, 'V2': float})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   V1      743 non-null    float64
 1   V2      743 non-null    float64
 2   V3      748 non-null    float64
 3   V4      748 non-null    float64
 4   V5      748 non-null    object
 5   Target  748 non-null    object
dtypes: float64(4), object(2)
memory usage: 35.2+ KB

In [7]:
df.describe()

               V1          V2            V3          V4
count  743.000000  743.000000    748.000000  748.000000
mean     9.562584    5.464334   1378.676471   34.282086
std      8.093527    5.799759   1459.826781   24.376714
min      0.000000    1.000000    250.000000    2.000000
25%      3.000000    2.000000    500.000000   16.000000
50%      8.000000    4.000000   1000.000000   28.000000
75%     14.000000    7.000000   1750.000000   50.000000
max     74.000000   50.000000  12500.000000   98.000000

In [8]:
df['Target'].value_counts()
df['V5'].value_counts()

Target
NO     570
YES    178
Name: count, dtype: int64

V5
NEGATIVE    748
Name: count, dtype: int64

In [30]:
numeric_cols = df[['V1', 'V2', 'V3', 'V4']]

outlier_count = {}

for col in numeric_cols.columns:
  col_data = df[col].dropna()

  Q1 = col_data.quantile(0.25)
  Q3 = col_data.quantile(0.75)

  iqr = Q3 - Q1

  lower_bound = Q1 - 1.5 * iqr
  upper_bound = Q1 + 1.5 * iqr

  outlier = col_data[(col_data < lower_bound) | (col_data > upper_bound)]
  outlier_count[col] = len(outlier)
  print(f'outlier count of {col} = {outlier_count[col]}')

outlier count of V1 = 105
outlier count of V2 = 114
outlier count of V3 = 117
outlier count of V4 = 98

In [34]:
from sklearn.impute import SimpleImputer

In [52]:
imputer = SimpleImputer(strategy='median')
v1_imputed = imputer.fit_transform(df[['V1']])
v1_imputed.mean()

np.float64(9.552139037433156)

In [54]:
imputer = SimpleImputer(strategy='mean')
v1_imputed = imputer.fit_transform(df[['V2']])
v1_imputed.mean()

np.float64(5.464333781965007)

In [48]:
from sklearn.impute import KNNImputer

In [50]:
imputer = KNNImputer()
v1_imputed = imputer.fit_transform(df[['V1']])
v1_imputed.mean()

np.float64(9.562584118438762)